---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: v1.14.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    bgp:
      enabled: false
    bpf:
      masquerade: true
    clustermesh:
      apiserver:
        kvstoremesh:
          enabled: false
        service:
          type: NodePort
        tls:
          auto:
            enabled: true
            method: cronJob
            schedule: 0 0 1 */4 *
      useAPIServer: true
    devices:
    - eth0
    enableIPv6Masquerade: false
    endpointRoutes:
      enabled: true
    externalIPs:
      enabled: true
    externalWorkloads:
      enabled: false
    extraConfig:
      enable-ipv6-ndp: "false"
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    ipam:
      mode: kubernetes
      operator:
        clusterPoolIPv4MaskSize: 16
        clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    ipv4:
      enabled: true
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    ipv6:
      enabled: false
    k8s-require-ipv4-pod-cidr: true
    k8s-require-ipv6-pod-cidr: false
    k8sClientRateLimit:
      burst: 25
      qps: 10
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    l2announcements:
      enabled: true
      leaseDuration: 300s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 10s
    localRedirectPolicy: true
    operator:
      replicas: 1
    routingMode: tunnel
    securityContext:
      privileged: true
    serviceAccounts:
      cilium:
        name: cilium
      operator:
        name: cilium-operator
    tunnel: vxlan